### ISSUE TITLE
Compiling on MacOS 64-bit

### ISSUE THREAD

**Issue by tjt263** [codydunne/netgrok#5]
Hi, I'm still interested in this project but can't seem to compile it.
I searched for an executable `.jar` file, but it seems it's not included with the source.

**Comment by tjt263** [comment]
**in:**
```
git clone https://github.com/codydunne/netgrok.git;
cd      ./netgrok;
sudo cp ./lib/darwin/32-bit\ i386/libjpcap.jnilib /Library/Java/Extensions;
sudo cp ./lib/jars/jpcap-0.7.jar                  /Library/Java/Extensions;

sed -i '' 's/Wireless=//' ./groups.ini

javac $(find . -name "*.java") -cp "./lib/jars/prefuse.jar:./lib/jars/jpcap-0.7.jar:./lib/jars/swing-layout-1.0.jar:./lib/darwin/32-bit i386/libjpcap.jnilib" -d .
java -cp "./:./lib/jars/prefuse.jar:./lib/jars/jpcap-0.7.jar:./lib/jars/swing-layout-1.0.jar:./lib/darwin/32-bit i386/libjpcap.jnilib" netgrok.NetGrokMain
```
- - -
**out:**

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Nov. 02, 2019 2:47:32 PM prefuse.action.ActionList run
WARNING: null
java.lang.NullPointerException
        at prefuse.data.column.ColumnMetadata.getMinimumRow(Unknown Source)
        at prefuse.util.DataLib.min(Unknown Source)
        at prefuse.util.DataLib.min(Unknown Source)
        at prefuse.action.assignment.DataSizeAction.setup(Unknown Source)
        at prefuse.action.EncoderAction.run(Unknown Source)
        at prefuse.action.ActionList.run(Unknown Source)
        at prefuse.action.ActionList.run(Unknown Source)
        at prefuse.action.Action.run(Unknown Source)
        at prefuse.activity.Activity.runActivity(Unknown Source)
        at prefuse.activity.ActivityManager.run(Unknown Source)
```

**Comment by tjt263** [comment]
**in:**
```
javac $(find . -name "*.java")  -cp "./lib/jars/prefuse.jar;./lib/jars/jpcap-0.7.jar;./lib/jars/swing-layout-1.0.jar"
```
- - -
**out:**
```
./src/netgrok/data/Data.java:16: error: package prefuse.action does not exist
import prefuse.action.Action;
                     ^
./src/netgrok/data/Data.java:18: error: package prefuse.data.event does not exist
import prefuse.data.event.TableListener;
                         ^
./src/netgrok/data/Data.java:19: error: package prefuse.data.expression does not exist
import prefuse.data.expression.Predicate;
                              ^
./src/netgrok/data/Data.java:20: error: package prefuse.data.io does not exist
import prefuse.data.io.TreeMLReader;
                      ^
./src/netgrok/data/Data.java:57: error: cannot find symbol
	private Tree groups = new Tree();
	        ^
  symbol:   class Tree
  location: class Data
./src/netgrok/data/Data.java:58: error: cannot find symbol
	private Graph ip_graph = new Graph();
	        ^
  symbol:   class Graph
  location: class Data
./src/netgrok/data/SimplePacket.java:8: error: package jpcap.packet does not exist
import jpcap.packet.IPPacket;
                   ^
./src/netgrok/data/SimplePacket.java:9: error: package jpcap.packet does not exist
import jpcap.packet.Packet;
                   ^
./src/netgrok/data/Data.java:213: error: cannot find symbol
	public Action getLockAction()
	       ^
  symbol:   class Action
  location: class Data
./src/netgrok/data/Data.java:218: error: cannot find symbol
	public Action getUnlockAction()
	       ^
  symbol:   class Action
  location: class Data
./src/netgrok/data/Data.java:224: error: cannot find symbol
	private HashMap<InetAddress,Node> node_map = new HashMap<InetAddress,Node>();
	                            ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:365: error: cannot find symbol
	public String getAllChildSubnets(Node group) {
	                                 ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:389: error: cannot find symbol
	public Graph getIPGraph() {
	       ^
  symbol:   class Graph
  location: class Data
./src/netgrok/data/Data.java:393: error: cannot find symbol
	public Tree getGroups() {
	       ^
  symbol:   class Tree
  location: class Data
./src/netgrok/data/Data.java:397: error: cannot find symbol
	private String getGroups(Node host) {
	                         ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:404: error: cannot find symbol
	private String getGroups(Node group, Node host) {		
	                         ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:404: error: cannot find symbol
	private String getGroups(Node group, Node host) {		
	                                     ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:421: error: cannot find symbol
	private void reRankByBandwidth(Node host) {
	                               ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:440: error: cannot find symbol
	private void reRankByBandwidth(Edge e) {
	                               ^
  symbol:   class Edge
  location: class Data
./src/netgrok/data/Data.java:460: error: cannot find symbol
	private void reRankByDegree(Node host) {
	                            ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:530: error: cannot find symbol
	public Node createNewNode(InetAddress address, boolean is_local, long time, int length)
	       ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:543: error: cannot find symbol
	public Edge createNewEdge(Node src_node, Node dst_node, SimplePacket p)
	                          ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:543: error: cannot find symbol
	public Edge createNewEdge(Node src_node, Node dst_node, SimplePacket p)
	                                         ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:543: error: cannot find symbol
	public Edge createNewEdge(Node src_node, Node dst_node, SimplePacket p)
	       ^
  symbol:   class Edge
  location: class Data
./src/netgrok/data/Data.java:702: error: cannot find symbol
	private void updateEdge(Edge e, SimplePacket p) {
	                        ^
  symbol:   class Edge
  location: class Data
./src/netgrok/data/Data.java:708: error: cannot find symbol
	private void updateNode(Node src_node, long time, int length) {
	                        ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:716: error: cannot find symbol
	private Set<TableListener> node_table_listeners = new HashSet<TableListener>();
	            ^
  symbol:   class TableListener
  location: class Data
./src/netgrok/data/Data.java:717: error: cannot find symbol
	private Set<TableListener> edge_table_listeners = new HashSet<TableListener>();
	            ^
  symbol:   class TableListener
  location: class Data
./src/netgrok/data/Data.java:719: error: cannot find symbol
	public void addTableListener(TableListener l, Table t)
	                             ^
  symbol:   class TableListener
  location: class Data
./src/netgrok/data/Data.java:719: error: cannot find symbol
	public void addTableListener(TableListener l, Table t)
	                                              ^
  symbol:   class Table
  location: class Data
./src/netgrok/data/Data.java:737: error: cannot find symbol
	public void addNodeTableListener(TableListener l) {
	                                 ^
  symbol:   class TableListener
  location: class Data
./src/netgrok/data/Data.java:793: error: cannot find symbol
	private Predicate filter_predicate = null;
	        ^
  symbol:   class Predicate
  location: class Data
./src/netgrok/data/Data.java:794: error: cannot find symbol
	public void setFilterPredicate(Predicate p)
	                               ^
  symbol:   class Predicate
  location: class Data
./src/netgrok/data/Data.java:837: error: cannot find symbol
	public static void getHostname(Node node) {
	                               ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/SelectListener.java:3: error: package prefuse.data does not exist
import prefuse.data.Edge;
                   ^
./src/netgrok/data/SelectListener.java:4: error: package prefuse.data does not exist
import prefuse.data.Node;
                   ^
./src/netgrok/data/SelectListener.java:5: error: package prefuse.data does not exist
import prefuse.data.Tuple;
                   ^
./src/netgrok/data/Data.java:865: error: cannot find symbol
	public void selectGroup(Node n)
	                        ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/Data.java:880: error: cannot find symbol
	public void selectEdge(Edge e)
	                       ^
  symbol:   class Edge
  location: class Data
./src/netgrok/data/Data.java:895: error: cannot find symbol
	public void selectNode(Node n)
	                       ^
  symbol:   class Node
  location: class Data
./src/netgrok/data/SelectListener.java:8: error: cannot find symbol
	public void nodeSelected(Node n);
	                         ^
  symbol:   class Node
  location: interface SelectListener
./src/netgrok/data/SelectListener.java:9: error: cannot find symbol
	public void edgeSelected(Edge e);
	                         ^
  symbol:   class Edge
  location: interface SelectListener
./src/netgrok/data/SelectListener.java:10: error: cannot find symbol
	public void groupSelected(Node n);
	                          ^
  symbol:   class Node
  location: interface SelectListener
./src/netgrok/data/Data.java:189: error: cannot find symbol
		public final Edge edge;
		             ^
  symbol:   class Edge
  location: class Data.EdgeTime
./src/netgrok/data/Data.java:191: error: cannot find symbol
		public EdgeTime(long time, Edge edge)
		                           ^
  symbol:   class Edge
  location: class Data.EdgeTime
./src/netgrok/data/SimplePacket.java:32: error: cannot find symbol
	public SimplePacket(IPPacket p)
	                    ^
  symbol:   class IPPacket
  location: class SimplePacket
./src/netgrok/data/Data.java:17: error: package prefuse.data does not exist
import prefuse.data.*;
^
./src/netgrok/data/Data.java:268: error: cannot find symbol
		public boolean contains(Node host) {
		                        ^
  symbol:   class Node
  location: class Group
./src/netgrok/data/EdgeTimeHistogram.java:9: error: package prefuse.action does not exist
import prefuse.action.Action;
                     ^
./src/netgrok/data/EdgeTimeHistogram.java:10: error: package prefuse.data does not exist
import prefuse.data.Table;
                   ^
./src/netgrok/data/EdgeTimeHistogram.java:11: error: package prefuse.data does not exist
import prefuse.data.Tuple;
                   ^
./src/netgrok/data/EdgeTimeHistogram.java:12: error: package prefuse.data.event does not exist
import prefuse.data.event.TupleSetListener;
                         ^
./src/netgrok/data/EdgeTimeHistogram.java:13: error: package prefuse.data.tuple does not exist
import prefuse.data.tuple.TupleSet;
                         ^
./src/netgrok/data/EdgeTimeHistogram.java:15: error: cannot find symbol
public class EdgeTimeHistogram extends Table implements Runnable, TupleSetListener {
                                       ^
  symbol: class Table
./src/netgrok/data/EdgeTimeHistogram.java:15: error: cannot find symbol
public class EdgeTimeHistogram extends Table implements Runnable, TupleSetListener {
                                                                  ^
  symbol: class TupleSetListener
./src/netgrok/data/EdgeTimeHistogram.java:59: error: cannot find symbol
	public class ETHUpdateActivity extends Action
	                                       ^
  symbol:   class Action
  location: class EdgeTimeHistogram
./src/netgrok/data/EdgeTimeHistogram.java:199: error: cannot find symbol
	public void tupleSetChanged(TupleSet arg0, Tuple[] arg1, Tuple[] arg2) {
	                            ^
  symbol:   class TupleSet
  location: class EdgeTimeHistogram
./src/netgrok/data/EdgeTimeHistogram.java:199: error: cannot find symbol
	public void tupleSetChanged(TupleSet arg0, Tuple[] arg1, Tuple[] arg2) {
	                                           ^
  symbol:   class Tuple
  location: class EdgeTimeHistogram
./src/netgrok/data/EdgeTimeHistogram.java:199: error: cannot find symbol
	public void tupleSetChanged(TupleSet arg0, Tuple[] arg1, Tuple[] arg2) {
	                                                         ^
  symbol:   class Tuple
  location: class EdgeTimeHistogram
./src/netgrok/data/FastEdgeTimeHistogram.java:9: error: package prefuse.action does not exist
import prefuse.action.Action;
                     ^
./src/netgrok/data/FastEdgeTimeHistogram.java:10: error: package prefuse.data does not exist
import prefuse.data.Table;
                   ^
./src/netgrok/data/FastEdgeTimeHistogram.java:11: error: package prefuse.data does not exist
import prefuse.data.Tuple;
                   ^
./src/netgrok/data/FastEdgeTimeHistogram.java:12: error: package prefuse.data.event does not exist
import prefuse.data.event.TupleSetListener;
                         ^
./src/netgrok/data/FastEdgeTimeHistogram.java:13: error: package prefuse.data.tuple does not exist
import prefuse.data.tuple.TupleSet;
                         ^
./src/netgrok/data/FilterPanel.java:30: error: package prefuse.data does not exist
import prefuse.data.Node;
                   ^
./src/netgrok/data/FilterPanel.java:31: error: package prefuse.data does not exist
import prefuse.data.Schema;
                   ^
./src/netgrok/data/FilterPanel.java:32: error: package prefuse.data does not exist
import prefuse.data.Tuple;
                   ^
./src/netgrok/data/FilterPanel.java:33: error: package prefuse.data does not exist
import prefuse.data.Table;
                   ^
./src/netgrok/data/FilterPanel.java:34: error: package prefuse.data.event does not exist
import prefuse.data.event.ExpressionListener;
                         ^
./src/netgrok/data/FilterPanel.java:35: error: package prefuse.data.expression does not exist
import prefuse.data.expression.ExpressionVisitor;
                              ^
./src/netgrok/data/FilterPanel.java:36: error: package prefuse.data.expression does not exist
import prefuse.data.expression.Predicate;
                              ^
./src/netgrok/data/FilterPanel.java:37: error: package prefuse.util.ui does not exist
import prefuse.util.ui.JRangeSlider;
                      ^
./src/netgrok/data/FilterPanel.java:38: error: package prefuse.data.event does not exist
import prefuse.data.event.TableListener;
                         ^
./src/netgrok/data/FilterPanel.java:53: error: cannot find symbol
public class FilterPanel extends JPanel implements VetoableChangeListener, Predicate, ChangeListener, KeyListener, TableListener{
                                                                           ^
  symbol: class Predicate
./src/netgrok/data/FilterPanel.java:53: error: cannot find symbol
public class FilterPanel extends JPanel implements VetoableChangeListener, Predicate, ChangeListener, KeyListener, TableListener{
                                                                                                                   ^
  symbol: class TableListener
./src/netgrok/data/FilterPanel.java:67: error: cannot find symbol
	private JRangeSlider bandwidthRangeSlider = null;
	        ^
  symbol:   class JRangeSlider
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:72: error: cannot find symbol
	private JRangeSlider degreeRangeSlider = null;
	        ^
  symbol:   class JRangeSlider
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:222: error: cannot find symbol
	private JRangeSlider getBandwidthSlider()
	        ^
  symbol:   class JRangeSlider
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:232: error: cannot find symbol
	private JRangeSlider getDegreeSlider()
	        ^
  symbol:   class JRangeSlider
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:242: error: cannot find symbol
	public void tableChanged(Table t, int start, int end, int col, int type) {
	                         ^
  symbol:   class Table
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:371: error: cannot find symbol
	private Set<ExpressionListener> expression_listeners = new HashSet<ExpressionListener>();
	            ^
  symbol:   class ExpressionListener
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:383: error: cannot find symbol
	public void addExpressionListener(ExpressionListener lstnr) {
	                                  ^
  symbol:   class ExpressionListener
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:387: error: cannot find symbol
	public void removeExpressionListener(ExpressionListener lstnr) {
	                                     ^
  symbol:   class ExpressionListener
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:391: error: cannot find symbol
	public Object get(Tuple t) {
	                  ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:396: error: cannot find symbol
	public boolean getBoolean(Tuple t) {
	                          ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:444: error: cannot find symbol
	public double getDouble(Tuple t) {
	                        ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:449: error: cannot find symbol
	public float getFloat(Tuple t) {
	                      ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:454: error: cannot find symbol
	public int getInt(Tuple t) {
	                  ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:459: error: cannot find symbol
	public long getLong(Tuple t) {
	                    ^
  symbol:   class Tuple
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:464: error: cannot find symbol
	public Class getType(Schema s) {
	                     ^
  symbol:   class Schema
  location: class FilterPanel
./src/netgrok/data/FilterPanel.java:468: error: cannot find symbol
	public void visit(ExpressionVisitor v) {
	                  ^
  symbol:   class ExpressionVisitor
  location: class FilterPanel
./src/netgrok/data/FunctionalExpression.java:7: error: package prefuse.data does not exist
import prefuse.data.Edge;
                   ^
./src/netgrok/data/FunctionalExpression.java:8: error: package prefuse.data does not exist
import prefuse.data.Node;
                   ^
./src/netgrok/data/FunctionalExpression.java:9: error: package prefuse.data does not exist
import prefuse.data.Schema;
                   ^
./src/netgrok/data/FunctionalExpression.java:10: error: package prefuse.data does not exist
import prefuse.data.Tuple;
                   ^
./src/netgrok/data/FunctionalExpression.java:11: error: package prefuse.data.column does not exist
import prefuse.data.column.IntColumn;
                          ^
./src/netgrok/data/FunctionalExpression.java:12: error: package prefuse.data.event does not exist
import prefuse.data.event.ExpressionListener;
                         ^
./src/netgrok/data/FunctionalExpression.java:13: error: package prefuse.data.expression does not exist
import prefuse.data.expression.Expression;
                              ^
./src/netgrok/data/FunctionalExpression.java:14: error: package prefuse.data.expression does not exist
import prefuse.data.expression.ExpressionVisitor;
                              ^
./src/netgrok/data/FunctionalExpression.java:16: error: cannot find symbol
public class FunctionalExpression implements Expression{
                                             ^
  symbol: class Expression
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
100 errors

```

**Comment by Nehachu** [comment]
Hello, were you able to resolve the issue? I too am interested in this project.
